### ISSUE TITLE
Sector faulted not appearing as an event in miner_sector_events

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/sentinel#124]

**Comment by placer14** [comment]
We found that we were performing the wrong diff when comparing states for miner sector events. The fix was applied in https://github.com/filecoin-project/lotus/pull/3715 and we are rebuilding the spacerace dataset on a completely new instance to merge the new (correct) state with our production dataset.

**Comment by frrist** [comment]
Closed via https://github.com/filecoin-project/lotus/pull/3715
