### ISSUE TITLE
Design a new schema for derived data and a process for populating it

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel#176]
The data extracted by Visor, Drone and other processes can be thought of as "raw" data where the schema is primarily optimised for ingest. Using this data for directly for analysis or dashboards faces several problems:

 1. Often many joins over large tables are needed to obtain the necessary data which hurts performance. 
 2. Beyond the minimum needed for the joins, the data isn't well indexed for many kinds of analysis queries. 
 3. Many queries require recursion to traverse the chain which don't scale to large ranges 
 4. There is no simple way to restrict data to just the consensus chain
 5. It's difficult to detect missing or incomplete data

We should eliminate these problems by creating a derived schema optimised for analysis. This will probably have flatter/wider tables that contain denormalised data that is easier to perform simple queries. For example there might be a table that combines messages with their receipts so the user doesn't need to remember to join using different heights.

Additionally this schema should have a defined process for populating it and keeping it up to date. This might be as simple as cronjob that refreshes some materialized views or could include software the transforms the data in some way.

*Success criteria*

The overall goal is to deliver a database using the new schema that contains data from the consensus chain automatically kept up to date.

 1. Data is added to derived database within 24 hours of ingest as raw data 
 2. Entire consensus chain to genesis is available
 3. All non-monitoring grafana dashboards are using the derived database

**Comment by iand** [comment]
Diagram showing where the derived data schema fits in sentinel

![Untitled document](https://user-images.githubusercontent.com/18375/107509547-a1494000-6b9a-11eb-8498-1232fa628540.png)

**Comment by iand** [comment]
An idea for one way to start could be to extract all the queries embedded in grafana charts and convert them to (materialized) views so the grafana chart becomes a simple select over a time range. That would form a basis schema that could be refactored to consolidate similar queries into more versatile views, adjusting the grafana query as necessary.

**Comment by ribasushi** [comment]
It would be great if more use-cases can be considered. For instance sentinel is not usable for my and several external collabs purposes ( need withinminute-realtime, guaranteed correct values ). The need is so acute that a parallel project is being built in part to satisfy this need. If there is a sync next week when @hsanjuan is back, consider involving me to perhaps align the designs/efforts.

**Comment by iand** [comment]
@ribasushi the canonical source of guaranteed correct values is the chain itself so it makes sense for realtime applications to gather blocks/messages directly (or via drone/lotus api). The derived data schema here is intended for long term analysis operations, generally after finality, sorry for not making that clear.

**Comment by ribasushi** [comment]
@iand this is what I am tying to raise: is a schema that is exclusively suitable for long-term analysis a project worth executing? I posit it has "insufficient PMF" ( to use the lingo of the day ) and am suggesting that we examine this in a sync meeting ( or async if scheduling is a problem )

**Comment by hsanjuan** [comment]
Hi, I would like to gain additional insight into concrete pains that pushes us towards working on this proposal as I find the descriptions of the issues it is trying to solve a bit vague:

> * Often many joins over large tables are needed to obtain the necessary data which hurts performance.

For example, we need to make a list of things which have performance impact that we cannot assume. I know few slow queries, but I don't know if making them faster justifies the complexity of new schemas and views. Would need to see case by case.

> * Beyond the minimum needed for the joins, the data isn't well indexed for many kinds of analysis queries.

We need to make a list of the "many kinds". I can think of 2 or 3 only, workaround-able.

> * Many queries require recursion to traverse the chain which don't scale to large ranges

I don't have knowledge of "many queries" that require recursion. We need to identify them.

> * There is no simple way to restrict data to just the consensus chain

In analysis the data is effectively restricted to the consensus chain by just tracking 200 epochs behind. I don't consider this a problem right now. We have tools to deal with the eventuality that the analysis DB gets polluted with non-consensus data if it ever comes to that.

If this is a monitoring issue, I would like to assess consequences of indexing non-consensus blocks in that specific context and whether those warrant an increase in complexity on schema and processing, always remembering that monitoring is not used for analysis.

> * It's difficult to detect missing or incomplete data

For many things, it is quite easy to detect missing data (heights missing). We have an observable that detects missing data this way.

For other things, it is indeed difficult and we got bitten before: i.e. only some deals in an epoch have been added, or some sector events are missing because primary keys are wrongly defined. This is tricky though, not sure derived views can easily uncover such errors.


---

So before jumping directly into a general architectural refactor, I'd like to be convinced. A list of concrete *deal breakers* and other *could be improved* things and how they'd get addressed would help.

We also need to acknowledge that we have a number of tables with derived data already, that visor is performing directly and that are quite suitable for direct use (`derived_gas_outputs`, `multisigs_transactions`, `parsed_messages` and such).

**Comment by iand** [comment]
> Hi, I would like to gain additional insight into concrete pains that pushes us towards working on this proposal as I find the descriptions of the issues it is trying to solve a bit vague:
> 
> > * Often many joins over large tables are needed to obtain the necessary data which hurts performance.
> 
> For example, we need to make a list of things which have performance impact that we cannot assume. I know few slow queries, but I don't know if making them faster justifies the complexity of new schemas and views. Would need to see case by case.

This is a fair point.
> 
> > * Beyond the minimum needed for the joins, the data isn't well indexed for many kinds of analysis queries.
> 
> We need to make a list of the "many kinds". I can think of 2 or 3 only, workaround-able.

I am thinking of the kind of queries that join blocks, block_headers, messages, and receipts to form a base set of executed messages of a type. It would be more efficient to have that data pre-joined but if you think it is limited to 2-3 cases then it's probably not worth it.


> 
> > * Many queries require recursion to traverse the chain which don't scale to large ranges
> 
> I don't have knowledge of "many queries" that require recursion. We need to identify them.

Any query that requires consensus chain only should be walking back from a known acceptable stateroot using a recursive query. Recursion is also used heavily in filflow.

> 
> > * There is no simple way to restrict data to just the consensus chain
> 
> In analysis the data is effectively restricted to the consensus chain by just tracking 200 epochs behind. I don't consider this a problem right now. We have tools to deal with the eventuality that the analysis DB gets polluted with non-consensus data if it ever comes to that.

I think this is an unsafe assumption. One example is the set of blocks indexed during catchup after the December chain halt. Regardless, we should also recommend this operational pattern to other users of visor and drone.

> 
> If this is a monitoring issue, I would like to assess consequences of indexing non-consensus blocks in that specific context and whether those warrant an increase in complexity on schema and processing, always remembering that monitoring is not used for analysis.
> 
> > * It's difficult to detect missing or incomplete data
> 
> For many things, it is quite easy to detect missing data (heights missing). We have an observable that detects missing data this way.
> 
> For other things, it is indeed difficult and we got bitten before: i.e. only some deals in an epoch have been added, or some sector events are missing because primary keys are wrongly defined. This is tricky though, not sure derived views can easily uncover such errors.
> 
> So before jumping directly into a general architectural refactor, I'd like to be convinced. A list of concrete _deal breakers_ and other _could be improved_ things and how they'd get addressed would help.
> 

This is not a refactor. It's an additional schema optimised for querying. We should expect query performance to decrease with continued data growth (except those constrained by narrow height ranges) and this issue is planning for that. 

The hard stop deal breaker will come when we are forced to physically partition the database when volume exceeds capacity which will limit or prevent certain types of joins. A derived data schema can be smaller and/or allow us to drop historic data from hot storage to prolong the life of current database.

Secondarily it may allow us to relax some constraints on the current schema to improve insert performance.

**Comment by hsanjuan** [comment]
Thanks Ian, fair points.

Re:

> I am thinking of the kind of queries that join blocks, block_headers, messages, and receipts to form a base set of executed messages of a type. It would be more efficient to have that data pre-joined but if you think it is limited to 2-3 cases then it's probably not worth it.
> 

derived_gas_outputs helps reducing the number of joins necessary for this particular case. This queries are friendly to time-filtering though. We have other tables (the ones that only show "changes" i.e. market_deal_states), that are more annoying... i.e. it is possible to see which sectors were terminated on a given time-frame. But knowing the average lifetime of them requires to filter since the beginning of time, because they could have been created any time. etc.

>  We should expect query performance to decrease with continued data growth

Yes, I agree that is very worrying.

**Comment by frrist** [comment]
Flagging that this work should also address concerns raised in: https://github.com/filecoin-project/sentinel-visor/issues/310
