### ISSUE TITLE
Design and implement anomaly detection framework

### ISSUE THREAD

**Issue by birdychang** [filecoin-project/sentinel#233]
We would like to prevent incident like [this one](https://www.notion.so/pl-strflt/Mainnet-Analysis-Dashboard-Reporting-Incorrect-Deals-Data-48eba37349ed4afba06f4ee191e5efc3).
Here're the steps we need to take:
- identify key datasets
- define key metrics (# of rows, specific biz logic like active deals, etc...)
- pick anomaly detection technique (SMA will do)
- implement the monitoring in TimescaleDB (Sentinel Alerts dash)
- implement the monitoring in BigQuery (prefect jobs)

**Comment by kasteph** [comment]
@birdychang These are the most important datasets and metrics. We should focus on these datasets: `market_deal_proposals`, `market_deal_states`, `derived_gas_outputs` , `miner_sector_events` to reduce the signal-to-noise ratio. Otherwise, if we have too many datasets, the value of the anomaly detection gets lost.

| dataset  | metric |
| ------------- | ------------- |
| `market_deal_proposals`, `market_deal_states`  | slashed/active deals |
| `derived_gas_outputs`  | gas usage, gas cost/deal, failed messages, gas usage |
| `derived_gas_outputs` , `miner_sector_events` | sector terminations |

Let me know if you have any further feedback, otherwise I will begin work on the aforementioned four datasets and metrics.

**Comment by birdychang** [comment]
@kasteph yes, that sounds good!

**Comment by birdychang** [comment]
Added `derived_gas_outputs` and `miner_sector_events` to [Key Dataset](https://protocollabs.grafana.net/d/-NdXhPQMz/sentinel-alerts?orgId=1&refresh=30m&from=now-24h&to=now#:~:text=Key-,Datasets,-market_deal_proposals) section and set up alerts.
